name: release

on:
    push:
        branches:
            - master
            - semver

jobs:
    release:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
            issues: write
            pull-requests: write

        steps:
            - name: checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: install build dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi nodejs

            - name: semantic release
              uses: cycjimmy/semantic-release-action@v4
              with:
                  extra_plugins: |
                      @semantic-release/git
                      @semantic-release/exec
                      @semantic-release/changelog
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
