name: release version

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v1.1.1
              with:
                  versionSpec: "5.x"

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v1.1.1

            - name: Use Version
              run: |
                  echo "Full SemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
                  echo "Major.Minor.Patch: ${{ steps.gitversion.outputs.majorMinorPatch }}"

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              if: github.ref == 'refs/heads/master'
              with:
                  tag_name: v${{ steps.gitversion.outputs.majorMinorPatch }}
                  name: Release BMS Firmware Version ${{ steps.gitversion.outputs.majorMinorPatch }}
                  body: |
                      **Version:** ${{ steps.gitversion.outputs.fullSemVer }}
                      **Commit Hash:** ${{ steps.gitversion.outputs.sha }}

                      Automatically generated by GitHub Actions.
                  draft: false
                  prerelease: false
                  files: |
                      bms/build/bms.bin
                      bms/build/bms.elf
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
